language: python
before_script:
  - rm .gitignore
script:
  - python build.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
  target_branch: gh-pages
